accepted = [
    "MIT",
    "Apache-2.0",
    "MPL-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "OpenSSL",
    "Unicode-3.0",
    "Unicode-DFS-2016",
    "Apache-2.0 WITH LLVM-exception",
    "AGPL-3.0",
    "Zlib",
    "EPL-2.0"
]

workarounds = [
    "ring"
]
