/**
 * N3rgy.Data.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TariffDto { 
    timestamp?: string;
    chargeType?: string | null;
    standingChargePence?: number | null;
    touPricePence?: number | null;
    block1PricePence?: number | null;
    block2PricePence?: number | null;
    block3PricePence?: number | null;
    block4PricePence?: number | null;
    blockThreshold1Kwh?: number | null;
    blockThreshold2Kwh?: number | null;
    blockThreshold3Kwh?: number | null;
}

